### ISSUE TITLE
add rsvp count / no. attending 

### ISSUE THREAD

**Issue by sayanee** [webuildorg/webuild-events#13]
add facebook and meetup.com

**Comment by sayanee** [comment]
e6c13c9dd274158a24ba62c51342c3cd3f86ca9d

**Comment by sayanee** [comment]
thanks @alyssaq for the idea :dancer:

**Comment by alyssaq** [comment]
:+1: Feel free to close my pull request

**Comment by sayanee** [comment]
😱 😭 i totally missed it. let me merge it instead!
