### ISSUE TITLE
Facebook events location field

### ISSUE THREAD

**Issue by notthetup** [webuildorg/webuild-events#22]
Facebook events with location set to an Event Venue aren't being returned with the postal address. 

for eg : https://www.facebook.com/events/1099895486733911/

**Comment by notthetup** [comment]
Seems that the `location` field in the v2.1 of the Graph API event object is deprecated.

https://developers.facebook.com/docs/graph-api/reference/v2.1/event/

**Comment by sayanee** [comment]
https://developers.facebook.com/docs/graph-api/reference/location/ this one - and we can also get the `lat`, `long` values
