### ISSUE TITLE
Timestamp format is inconsistent.

### ISSUE THREAD

**Issue by notthetup** [webuildorg/webuild-events#23]
In certain modules, the `start_time` and `end_time` fields are populated directly from the response of the event platform API. This makes the time stamps in inconsistent as some APIs don't return a proper ISO 8601 String (uhm.. Eventbrite).

https://github.com/webuildorg/webuild-events/blob/master/events/eventbriteEvents.js#L59

We should parse and generate our own Time stamp string instead of relying on the API.

![screenshot 2016-06-16 10 00 26](https://cloud.githubusercontent.com/assets/553140/16103255/5e941e84-33a9-11e6-83ac-1d5dbfd80887.jpg)

**Comment by sayanee** [comment]
ok fixed! Now eventbrite events have the same time format:

![image](https://cloud.githubusercontent.com/assets/413879/16137377/3b51603c-3465-11e6-8d04-97bf6eccba44.png)
